[project]
name = "isekai-data-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "ipykernel>=6.29.5",
    "pandas>=2.2.3",
    "seaborn>=0.13.2",
]
